name: CI Pipeline - Node.js with Docker

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build: 
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: Install Gitleaks
          run: |
            curl -sSfL https://github.com/gitleaks/gitleaks/releases/download/v8.18.4/gitleaks_8.18.4_linux_x64.tar.gz | tar -xz
            mv gitleaks /usr/local/bin/
        
        - name: Run Gitleaks Scan
          run: |
            gitleaks detect --source . --config .gitleaks.toml --report-format json --report-path secret-report.json

        - name: Print report
          run: | 
            cat secret-report.json 


