name: CI Pipeline - Node.js with Docker

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build: 
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: Install Gitleaks
          uses: zricethezav/gitleaks-action@v2
          with:
            config-path: .gitleaks.toml
            report-path: secret-report.json
            report-format: json

        - name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
           name: secret-report
           path: secret-report.json

        
        - name: Check for secrets
          run: |
            if [ -s secret-report.json ] && [ "$(jq '. | length' secret-report.json)" -gt 0 ]; then
              echo "Secrets found in code. Aborting pipeline."
              cat secret-report.json
              exit 1
            fi
        
        
