name: CI Pipeline - Node.js with Docker

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build: 
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: Install Gitleaks
          run: |
            curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
            echo ls -l
            chmod +x gitleaks
            sudo mv gitleaks /usr/local/bin/
        
        - name: Run Gitleaks Scan
          run: |
            gitleaks detect --source . --config .gitleaks.toml --report-format json --report-path secret-report.json

        - name: Print report
          run: | 
            cat secret-report.json 


